### ISSUE TITLE
Could it serialize NDS format struct such as *.ds now?

### ISSUE THREAD

**Issue by fszhaoholo** [ndsev/zserio-tutorial-cpp#1]
As the title.

**Comment by fklebert** [comment]
zserio is not compatible with the old NDS-internal DataScript format. Next Generation of NDS format will be using zserio, but for now you will have to work with the "RDS tool" to generate code for NDS 2.x.y DataScript.

**Comment by fszhaoholo** [comment]
That is not  very good news.  thanks for your reply.
